import { PricingSeason, Amenity } from './types';

// Image Placeholders (simulating "nano banana" generation with Picsum for functional prototype)
// In a real build, these would be local files in /public/images/ generated by the model.
export const IMAGES = {
  hero: "https://picsum.photos/seed/eggers_living/1920/1080",
  livingRoom: "https://picsum.photos/seed/eggers_interior/800/600",
  bedroom: "https://picsum.photos/seed/eggers_bed/800/600",
  kitchen: "https://picsum.photos/seed/eggers_kitchen/800/600",
  bathroom: "https://picsum.photos/seed/eggers_bath/800/600",
  exterior: "https://picsum.photos/seed/eggers_house/800/600",
  beach: "https://picsum.photos/seed/cuxhaven_watt/1920/800",
  detail1: "https://picsum.photos/seed/decor1/400/600",
  detail2: "https://picsum.photos/seed/decor2/400/600",
  detail3: "https://picsum.photos/seed/decor3/400/600",
};

export const SITE_DATA = {
  name: "Ferienwohnung Eggers",
  location: "Cuxhaven-Sahlenburg",
  email: "kontakt@ferienwohnung-eggers.de",
  phone: "+49 4721 123456",
  address: "Am Sahlenburger Strand 12, 27476 Cuxhaven",
};

export const AMENITIES: Amenity[] = [
  { icon: "Wifi", title: "Highspeed WLAN", description: "Kostenloses Glasfaser-Internet für Home Office und Entertainment." },
  { icon: "Coffee", title: "Vollausgestattete Küche", description: "Induktionsherd, Spülmaschine, Nespresso-Maschine." },
  { icon: "Sun", title: "Südbalkon", description: "Genießen Sie die Sonne mit Blick ins Grüne." },
  { icon: "Car", title: "Privatparkplatz", description: "Reservierter Stellplatz direkt am Haus inklusive E-Ladesäule." },
  { icon: "Monitor", title: "Smart TV", description: "55 Zoll 4K TV mit Netflix und Satellitenanschluss." },
  { icon: "Wind", title: "Allergikerfreundlich", description: "Keine Haustiere, spezielle Filteranlagen und Bodenbeläge." },
];

export const SEASONS: PricingSeason[] = [
  { name: "Nebensaison", period: "Jan - Mar, Nov - Dez", pricePerNight: 85, minStay: 3 },
  { name: "Zwischensaison", period: "Apr - Jun, Sep - Okt", pricePerNight: 110, minStay: 5 },
  { name: "Hauptsaison", period: "Jul - Aug, Feiertage", pricePerNight: 145, minStay: 7 },
];

export const ROUTES = [
  { path: "/", label: "Startseite" },
  { path: "/ausstattung", label: "Ausstattung" },
  { path: "/galerie", label: "Galerie" },
  { path: "/lage", label: "Lage" },
  { path: "/preise", label: "Preise" },
  { path: "/kontakt", label: "Kontakt" },
];